apiVersion: v1
kind: ServiceAccount
metadata:
  name: truststore-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: truststore-sa
  namespace: keystore-site-verify